apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: app1
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/solkoff/nginx:0.1.5
        ports:
        - containerPort: 80